# ==========================================================
# scoring.py
# ==========================================================

"""
Scoring Module

Responsibilities
----------------
1. Calculate JD Score
2. Calculate Quality Score
3. Calculate Final Score
4. Apply Confidence Penalties

This module DOES NOT perform feature extraction.
It only consumes features generated by the other modules.
"""


# ==========================================================
# Score Weights
# ==========================================================

JD_SCORE_WEIGHTS = {

    "required_skill": 22,
    "semantic": 16,
    "role": 10,
    "domain": 7,
    "preferred_skill": 5

}


QUALITY_SCORE_WEIGHTS = {

    "retrieval_strength": 8,
    "ai_strength": 6,
    "experience": 4,
    "career_progression": 3,
    "education": 2,
    "production": 3,
    "recent_experience": 2,
    "company_type": 1,
    "credibility": 1

}


# ==========================================================
# Helper
# ==========================================================

def normalize(value, maximum):

    if maximum <= 0:
        return 0

    return min(value / maximum, 1)


def normalize_score_distribution(scores):
    """Assign a distinct, reliable score to every candidate while preserving ordering."""
    if not scores:
        return []

    if len(scores) == 1:
        return [1.0]

    order = sorted(range(len(scores)), key=lambda index: (-scores[index], index))
    normalized = [0.0] * len(scores)
    total = len(scores)

    for position, index in enumerate(order):
        if position == 0:
            normalized[index] = 1.0
        elif position == total - 1:
            normalized[index] = 0.05
        else:
            rank_ratio = position / (total - 1)
            base = 1.0 - (rank_ratio * 0.95)
            jitter = (total - position) / (total * 1000)
            normalized[index] = round(max(0.05, base + jitter), 6)

    return normalized


# ==========================================================
# JD Score
# ==========================================================

def calculate_jd_score(features):
    """
    JD Alignment Score

    Maximum = 60
    """

    required_skill = (
        features.get(
            "required_skill_score",
            0
        ) / 10
    )

    preferred_skill = (
        features.get(
            "preferred_skill_score",
            0
        ) / 10
    )

    semantic = features.get(
        "semantic_score",
        0
    )

    role = (
        features.get(
            "role_match_score",
            0
        ) / 10
    )

    domain = (
        features.get(
            "domain_match_score",
            0
        ) / 10
    )

    jd_score = (

        required_skill
        * JD_SCORE_WEIGHTS["required_skill"]

        +

        semantic
        * JD_SCORE_WEIGHTS["semantic"]

        +

        role
        * JD_SCORE_WEIGHTS["role"]

        +

        domain
        * JD_SCORE_WEIGHTS["domain"]

        +

        preferred_skill
        * JD_SCORE_WEIGHTS["preferred_skill"]

    )

    return {

        "jd_score":
            round(
                jd_score,
                2
            )

    }


# ==========================================================
# Quality Score
# ==========================================================

def calculate_quality_score(
    features,
    max_ai_strength,
    max_retrieval_strength
):
    """
    Candidate Quality Score

    Maximum = 30
    """

    ai = normalize(

        features.get(
            "normalized_ai_skill_strength",
            0
        ),

        max_ai_strength

    )

    retrieval = normalize(

        features.get(
            "normalized_retrieval_strength",
            0
        ),

        max_retrieval_strength

    )

    experience = normalize(

        features.get(
            "years_of_experience",
            0
        ),

        8

    )

    career = normalize(

        features.get(
            "career_progression_score",
            0
        ),

        10

    )

    education = normalize(

        features.get(
            "education_score",
            0
        ),

        10

    )

    production = normalize(

        features.get(
            "production_score",
            0
        ),

        10

    )

    recent = normalize(

        features.get(
            "recent_experience_score",
            0
        ),

        10

    )

    company = normalize(

        features.get(
            "company_type_score",
            0
        ),

        10

    )

    credibility = normalize(

        features.get(
            "credibility_score",
            10
        ),

        10

    )

    quality = (

        retrieval
        * QUALITY_SCORE_WEIGHTS["retrieval_strength"]

        +

        ai
        * QUALITY_SCORE_WEIGHTS["ai_strength"]

        +

        experience
        * QUALITY_SCORE_WEIGHTS["experience"]

        +

        career
        * QUALITY_SCORE_WEIGHTS["career_progression"]

        +

        education
        * QUALITY_SCORE_WEIGHTS["education"]

        +

        production
        * QUALITY_SCORE_WEIGHTS["production"]

        +

        recent
        * QUALITY_SCORE_WEIGHTS["recent_experience"]

        +

        company
        * QUALITY_SCORE_WEIGHTS["company_type"]

        +

        credibility
        * QUALITY_SCORE_WEIGHTS["credibility"]

    )

    return {

        "quality_score":
            round(
                quality,
                2
            )

    }


# ==========================================================
# Confidence
# ==========================================================

def calculate_confidence(features):
    """
    Confidence multiplier.

    Penalizes weak matches.
    """

    confidence = 1.0

    if features.get(
        "required_skill_score",
        0
    ) < 3:

        confidence *= 0.70

    if features.get(
        "semantic_score",
        0
    ) < 0.40:

        confidence *= 0.80

    if features.get(
        "role_match_score",
        0
    ) == 0:

        confidence *= 0.60

    if features.get(
        "credibility_score",
        10
    ) < 5:

        confidence *= 0.80

    return confidence


# ==========================================================
# Final Score
# ==========================================================

def calculate_final_score(
    features,
    jd_score,
    quality_score,
    behavior_score
):
    """
    Final candidate score.

    Maximum raw score ≈ 100
    """

    raw_score = (

        jd_score

        +

        quality_score

        +

        behavior_score

    )

    confidence = calculate_confidence(
        features
    )

    final_score = raw_score * confidence

    return {

        "raw_score":
            round(
                raw_score,
                2
            ),

        "confidence":
            round(
                confidence,
                3
            ),

        "score":
            round(
                final_score / 100,
                4
            )

    }


# ==========================================================
# Complete Scoring Pipeline
# ==========================================================

def calculate_scoring_pipeline(
    features,
    max_ai_strength,
    max_retrieval_strength
):
    """
    Complete scoring pipeline.
    """

    jd = calculate_jd_score(
        features
    )

    quality = calculate_quality_score(

        features,

        max_ai_strength,

        max_retrieval_strength

    )

    behavior = features.get(
        "behavior_score",
        0
    )

    final = calculate_final_score(

        features,

        jd["jd_score"],

        quality["quality_score"],

        behavior

    )

    result = {}

    result.update(jd)

    result.update(quality)

    result.update({

        "behavior_score":
            behavior

    })

    result.update(final)

    return result